theme: jekyll-theme-architect
title: Invoicing
description: Webb application for generate sale invoice. I made this applciation for personal use. And becouse the result was great, I cosidered to make it public.