DROP DATABASE  IF EXISTS `invoicing-demo` ;
CREATE DATABASE  IF NOT EXISTS `invoicing-demo` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `invoicing-demo`;
CREATE USER IF NOT EXISTS 'invoicing-demo'@'%' IDENTIFIED BY 'generic8iNbR7';
GRANT SELECT, INSERT, UPDATE, DELETE ON *.* TO 'invoicing-demo'@'%'
REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;